usb: include stdlib.h for malloc declaration
Yocto Walnascar building qdl leads to following error:

  | usb.c: In function 'usb_init':
  | usb.c:295:34: error: implicit declaration of function 'malloc' [-Wimplicit-function-declaration]
  |   295 |         struct qdl_device *qdl = malloc(sizeof(struct qdl_device_usb));

Fix this by including the required header directly.

Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>